apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:  userservice-rs
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      name: userservice
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: vijramire/microserviceapp
          imagePullPolicy: IfNotPresent
      restartPolicy: Always